export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const  UPDATE_CURRENT_PROJECT = 'UPDATE_CURRENT_PROJECT';
export const CURRENT_VIEW = 'CURRENT_VIEW';
